name: Create static assets
on:
  release:
    types: [published, edited]
jobs:
  static-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch @${{github.ref_name}}
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref_name}}


      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'


      - name: Download requirements
        run: |
          pip install -r requirements.txt
          cp .env.example .env


      - name: Run collectstatic
        run: python manage.py collectstatic --noinput
        env:
          MODE: PRODUCTION
          DEBUG: False


      - name: Create artifact
        run: zip -r mathesar-v${{github.ref_name}}.zip . -x '*.git*'


      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: mathesar-v${{github.ref_name}}.zip
